altinity-clickhouse-operator:
  serviceMonitor:
    enabled: true
  dashboards:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
    additionalLabels:
      grafana_dashboard: "1"

