{
 "title": "Internal Grafana Stats",
 "description": "Data Proxy request timings (percentiles), dashboard loads, logins etc, Prometheus version.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "No. of current grafana users",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "grafana_live_node_num_users",
     "legendFormat": "Number of unique users connected"
    },
    { "expr": "grafana_live_node_num_clients", "legendFormat": "Number of clients connected" }
   ]
  },
  {
   "title": "Alerts trigered",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "changes(grafana_alerting_notifications_total{integration=\"email\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(grafana_alerting_notifications_total{integration=\"teams\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(grafana_alerting_notifications_total{integration=\"telegram\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(grafana_alerting_notifications_total{integration=\"webhook\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total no. of active Alerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "grafana_alerting_alertmanager_alerts{state=\"active\"}",
     "legendFormat": "amount of active alerts"
    }
   ]
  },
  {
   "title": "Grafana no. of dashboards",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 19 },
   "targets": [
    { "expr": "grafana_stat_totals_dashboard", "legendFormat": "total amount of dashboards" }
   ]
  },
  {
   "title": "Dashboard count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana no. of plugins",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "targets": [
    { "expr": "plugins_active_instances", "legendFormat": "total amount of dashboards" }
   ]
  },
  {
   "title": "Number of logins 24h",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "changes(grafana_api_login_post_total[24h])",
     "legendFormat": "api login post counter"
    }
   ]
  },
  {
   "title": "Grafana to Datasource request past 24h",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(grafana_datasource_request_total[24h])",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Number of users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 37 },
   "targets": [
    { "expr": "grafana_stat_active_users", "legendFormat": "No. of all Users" },
    {
     "expr": "grafana_stat_totals_active_admins",
     "legendFormat": "No. of Admins"
    },
    {
     "expr": "grafana_stat_totals_active_editors",
     "legendFormat": "No. of Editors"
    },
    {
     "expr": "grafana_stat_totals_active_viewers",
     "legendFormat": "No. of Viewers"
    }
   ]
  },
  {
   "title": "Grafana organization data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 37 },
   "targets": [
    { "expr": "grafana_stat_total_orgs", "legendFormat": "No. of organizations" },
    {
     "expr": "grafana_stat_totals_library_panels",
     "legendFormat": "totals_library_panels"
    },
    { "expr": "grafana_stat_totals_folder", "legendFormat": "totals_folder" }
   ]
  },
  {
   "title": "Alerting number of notifications sent 24h - legacy grafana",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "changes(grafana_alerting_notification_sent_total[24h])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "alerting_result_total Alerting 24h - legacy grafana",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "grafana_alerting_notifications_total{integration=\"email\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "alerting_result_total OK 24h - legacy grafana",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 53 },
   "targets": [
    {
     "expr": "changes(grafana_alerting_result_total{state=\"ok\"}[24h])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "alerting_result_total no_data 24h - legacy grafana",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 53 },
   "targets": [
    {
     "expr": "changes(grafana_alerting_result_total{state=\"no_data\"}[24h])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "alerting_result_total pending 24h",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 53 },
   "targets": [
    {
     "expr": "changes(grafana_alerting_result_t[24h])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "alerting_result_total unknown 24h - legacy grafana",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 53 },
   "targets": [
    {
     "expr": "changes(grafana_alerting_result_total{state=\"unknown\"}[24h])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total no. of defined/active Alerts - legacy grafana",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 60 },
   "targets": [
    { "expr": "grafana_alerting_active_alerts", "legendFormat": "amount of active alerts" }
   ]
  }
 ]
}