{
 "title": "Kubernetes Daemonset metrics",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics ",
 "tags": [
  "kubernetes",
  "k8s"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_daemonset_metadata_generation,namespace)"
    }
   },
   {
    "name": "Daemonset",
    "query": {
     "query": "label_values(kube_daemonset_metadata_generation{namespace=\"$Namespace\"},daemonset)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$Namespace\", pod=~\"$Daemonset-[a-z0-9]{5}\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "kube_pod_status_phase{namespace=~\"$Namespace\",  pod=~\"$Daemonset.+\"} >= 1",
     "legendFormat": "{{ pod }} in status {{ phase }}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{namespace=~\"$Namespace\", daemonset=~\"$Daemonset\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{namespace=~\"$Namespace\", daemonset=~\"$Daemonset\"}",
     "legendFormat": "{{daemonset}}"
    }
   ]
  },
  {
   "title": "Pods restart count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum_over_time(kube_pod_container_status_restarts_total{namespace=~\"$Namespace\", pod=~\"$Daemonset.+\"}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Usage resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pods CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", pod=~\"$Daemonset.+\"}[1m])) by (pod)",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{clusterID=\"$cluster\", datacenter=\"$datacenter\", namespace=\"$Namespace\", pod=~\"$$Daemonset.+\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "Limits {{ pod }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$Namespace\", pod=~\"$Daemonset.+\",image!=\"\"}) by (pod)",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{clusterID=\"$cluster\", datacenter=\"$datacenter\", namespace=\"$Namespace\", pod=~\"$Daemonset.+\", resource=\"memory\"}) by (pod)",
     "legendFormat": "Limits {{ pod }}"
    }
   ]
  },
  {
   "title": "Pods network bytes transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{pod=~\"$Daemonset.+\", namespace=~\"$Namespace\"}[1m])) by (pod, node)",
     "legendFormat": "<- {{ pod }} on {{ node }}"
    }
   ]
  },
  {
   "title": "Pods network bytes received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"$Daemonset.+\",  namespace=~\"$Namespace\"}[1m])) by (pod, node)",
     "legendFormat": "-> {{ pod }} on {{ node }}"
    }
   ]
  },
  {
   "title": "Pods sockets usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_sockets{ namespace=~\"$Namespace\", pod=~\"$Daemonset.+\",image!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Storage IO - Distribution(Pod - Read & Writes) IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container!=\"\",  namespace=~\"$Namespace\", pod=~\"$Daemonset.+\"}[5m])))",
     "legendFormat": "{{ pod }} - Reads"
    },
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_writes_total{container!=\"\", clusterID=\"$cluster\", datacenter=\"$datacenter\", namespace=~\"$Namespace\", pod=~\"$Daemonset.+\"}[5m])))",
     "legendFormat": "{{ pod }} - Writes"
    }
   ]
  },
  {
   "title": "Storage IO - Distribution(Pod - Read & Writes) ThroughPut",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\",  namespace=~\"$Namespace\", pod=~\"$Daemonset.+\"}[5m]))",
     "legendFormat": "{{ pod }} - Reads"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{container!=\"\", clusterID=\"$cluster\", datacenter=\"$datacenter\", namespace=~\"$Namespace\", pod=~\"$Daemonset.+\"}[5m]))",
     "legendFormat": "{{ pod }} - Writes"
    }
   ]
  },
  { "title": "Usage resources inside pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "All processes CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",  namespace=~\"$Namespace\", pod=~\"$Daemonset.+\"}[1m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",  namespace=~\"$Namespace\", pod=~\"$Daemonset.+\"}) by (id, pod)",
     "legendFormat": "{{ pod }}-{{ id }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\", namespace=~\"$Namespace\", pod=~\"$Daemonset.+\"}[1m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\", clusterID=\"$cluster\", datacenter=\"$datacenter\", namespace=~\"$Namespace\", pod=~\"$Daemonset.+\"}[1m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}