{
 "title": "Fluent",
 "description": "This is a simple dashboard for: https://github.com/banzaicloud/logging-operator utilising Fluent-bit and Fluentd",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(node_cpu_seconds_total, cluster)"
   },
   {
    "name": "fluentdplugin",
    "label": "Fluentd Plugin",
    "query": "label_values(fluentd_output_status_emit_records, plugin_id)"
   },
   {
    "name": "fluentbit",
    "query": "label_values(fluentbit_input_bytes_total,pod)"
   },
   {
    "name": "fluentd",
    "query": "label_values(fluentd_output_status_emit_count,pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregated Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fluent-bit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*fluentbit.*\",cluster=\"$cluster\"})",
     "legendFormat": "Active Fluent-bit"
    }
   ]
  },
  {
   "title": "Fluentd",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*fluentd.*\",pod!~\".*config.*\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Fluentbit Input Record",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[1m]))"
    }
   ]
  },
  {
   "title": "Fluentbit Output Records",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total[1m]))"
    }
   ]
  },
  {
   "title": "Fluentd Router records/s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_router_records_total[1m]))"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Bad Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\",status=\"true\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Fluentbit Input Bytes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total[5m]))"
    }
   ]
  },
  {
   "title": "Fluentbit Output Bytes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total[5m]))"
    }
   ]
  },
  {
   "title": "Fluentd Output Records",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_emit_records{plugin_id=~\"^(flow|clusterflow):.*:.*:(output|clusteroutput).*:.*$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "fluentd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Fluentd Records by Plugin",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(fluentd_output_status_emit_count{pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}[5m])",
       "legendFormat": "{{ plugin_id }}/{{pod}}"
      }
     ]
    },
    {
     "title": "Top Aggregated Fluentd Routes",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "topk(5, sum(rate(fluentd_router_records_total[1m])) by (flow, id))"
      }
     ]
    },
    {
     "title": "Fluentd Output Buffer",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluentd_output_status_buffer_total_bytes{pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}",
       "legendFormat": "{{ plugin_id }}"
      },
      {
       "expr": "fluentd_output_status_buffer_queue_length{pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}"
      }
     ]
    },
    {
     "title": "Fluentd Buffer Disk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{pod=~\"$fluentd\",mountpoint=\"/buffers\",endpoint=\"buffer-metrics\", fstype!=\"\"} - node_filesystem_free_bytes{pod=~\"$fluentd\",mountpoint=\"/buffers\",endpoint=\"buffer-metrics\", fstype!=\"\"}",
       "legendFormat": "Used: {{pod}}"
      },
      {
       "expr": "node_filesystem_size_bytes{pod=~\"$fluentd\",mountpoint=\"/buffers\",endpoint=\"buffer-metrics\", fstype!=\"\"}",
       "legendFormat": "Total: {{pod}}"
      }
     ]
    },
    {
     "title": "Fluentd Output Error and Retry",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_retry_count{pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}[1m])) by (pod)",
       "legendFormat": "Retry {{pod}}"
      },
      {
       "expr": "sum(rate(fluentd_output_status_num_errors{pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}[1m])) by (pod)",
       "legendFormat": "Error {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "fluentbit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fluentbit Input Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Input Record",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Records",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Retries/Fails",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total{pod=~\"$fluentbit\"}[1m])) by (pod, name)",
     "legendFormat": "Retries {{ pod }}/{{name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{pod=~\"$fluentbit\"}[1m])) by (pod, name)",
     "legendFormat": "Failed {{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{pod=~\"$fluentbit\"}[1m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Dropped Records",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_dropped_records_total{pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Retried Records",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retried_records_total{pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  }
 ]
}