{
 "title": "Kubernetes statefulset metrics",
 "description": "Monitors Kubernetes statefulsets in cluster using Prometheus. Shows overall cluster CPU / Memory of statefulsets, replicas in each statefulset. Uses Kube state metrics and cAdvisor metrics ",
 "tags": [
  "kubernetes",
  "k8s"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_statefulset_labels,namespace)"
    }
   },
   {
    "name": "statefulset",
    "query": {
     "query": "label_values(kube_statefulset_labels{namespace=\"$Namespace\"},statefulset)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$Namespace\", pod=~\"$statefulset-[0-9]+\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "kube_pod_status_phase{ namespace=~\"$Namespace\", pod=~\"$Pod\"} >= 1",
     "legendFormat": "{{ pod }} in status {{ phase }}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_available{namespace=~\"$Namespace\", statefulset=~\"$statefulset\"}"
    }
   ]
  },
  {
   "title": "Pods restart count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum_over_time(kube_pod_container_status_restarts_total{ namespace=~\"$Namespace\", pod=~\"$Pod\"}[$__interval])",
     "legendFormat": "{{ pod }}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Usage resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pods CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", pod=~\"$Pod\"}[1m])) by (pod)",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{datacenter=\"$datacenter\", clusterID=\"$cluster\", namespace=\"$Namespace\", pod=~\"$Pod\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "Limits {{ pod }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$Namespace\", pod=~\"$Pod\",image!=\"\"}) by (pod)",
     "legendFormat": "Usage {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{datacenter=\"$datacenter\", clusterID=\"$cluster\", namespace=\"$Namespace\", pod=~\"$Pod\", resource=\"memory\"}) by (pod)",
     "legendFormat": "Limits {{ pod }}"
    }
   ]
  },
  {
   "title": "Pods network bytes transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{pod=~\"$Pod\",  namespace=~\"$Namespace\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "Pods network bytes received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"$Pod\",  namespace=~\"$Namespace\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    }
   ]
  },
  {
   "title": "Pods sockets usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_sockets{ namespace=~\"$Namespace\", pod=~\"$Pod\",image!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Storage IO - Distribution(Pod - Read & Writes) IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{ container!=\"\",  namespace=~\"$Namespace\", pod=~\"$Pod\"}[5m])))",
     "legendFormat": "{{ pod }} - Reads"
    },
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_writes_total{datacenter=\"$datacenter\", container!=\"\", clusterID=\"$cluster\", namespace=~\"$Namespace\", pod=~\"$Pod\"}[5m])))",
     "legendFormat": "{{ pod }} - Writes"
    }
   ]
  },
  {
   "title": "Storage IO - Distribution(Pod - Read & Writes) ThroughPut",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{ container!=\"\", namespace=~\"$Namespace\", pod=~\"$Pod\"}[5m]))",
     "legendFormat": "{{ pod }} - Reads"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{datacenter=\"$datacenter\", container!=\"\",clusterID=\"$cluster\", namespace=~\"$Namespace\", pod=~\"$Pod\"}[5m]))",
     "legendFormat": "{{ pod }} - Writes"
    }
   ]
  },
  { "title": "Usage resources inside pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "All processes CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",pod=~\"$Pod\",  namespace=~\"$Namespace\"}[1m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod=~\"$Pod\",  namespace=~\"$Namespace\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod=~\"$Pod\",  namespace=~\"$Namespace\"}[1m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",pod=~\"$Pod\", clusterID=\"$cluster\", namespace=~\"$Namespace\"}[1m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}