apiVersion: v2
name: fluent-bit
description: Chart for Fluent-bit
type: application
version: 0.1.0
dependencies:
- name: fluent-bit
  version: 0.47.10
  repository: https://fluent.github.io/helm-charts
